name: Test BRO REST API on Schedule

on:
  schedule:
    - cron:  '*/5 * * * *' # Every 6th hour 0 (*/6) * * * these tests are run

jobs:

  build:
    name: Scheduled BRO REST API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov coverage
        pip install -r requirements.txt
    - name: Build coverage file
      run: |
        pytest --cov=bro --cov-config=.coveragerc --junitxml=report.xml --cov-report=html:html/test-coverage-results
        coverage report --skip-covered || true
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-results
        path: html/test-coverage-results
      if: ${{ always() }}
    - name: Download Coverage results
      uses: actions/download-artifact@v3
      with:
        name: coverage-results
